apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "catalog-api-auth"
spec:
  targets:
    - name: catalog-api
  origins:
    - jwt:
        issuer: "http://keycloak.devlocal/auth/realms/samply"
        jwksUri: "http://keycloak-http.default.svc.cluster.local/auth/realms/samply/protocol/openid-connect/certs"
        trigger_rules:
          - excluded_paths:
              - exact: /
              - prefix: /swagger-ui
              - exact: /openapi
  principalBinding: USE_ORIGIN
---
# apiVersion: config.istio.io/v1alpha2
# kind: rule
# metadata:
#   name: auth-header
#   namespace: istio-system
# spec:
#   actions:
#     - handler: keyval.istio-system
#       instances: [keyval]
#   request_header_operations:
#     - name: X-user-id
#       values:
#         - request.auth.claims["sub"]
